### ISSUE TITLE
Need a template for all the data to be recorded

### ISSUE THREAD

**Issue by aneeshsharma** [aneeshsharma/car-pollution-server#6]
Create a JSON template for recorded data

**Comment by amalpavithran** [comment]
[
  '{{repeat(5)}}',
  {
    journeyId: '{{objectId()}}',
    startTime: '{{date()}}',
    endTime: function(tags){
      return tags.date() + this.startTime;
    },
    data:[
      '{{repeat(100,200)}}',
      {
        emission: '{{integer(200,900)}}',
        speed: '{{integer(0,200)}}',
        engineTemp: '{{integer(45,200)}}°C',
        ambientTemp: '{{integer(-45,45)}}°C'
      }
    ]
  }
]

**Comment by amalpavithran** [comment]
Use this in json-generator.com
